site_name: KiloAlpha Security Lab
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange # High-visibility for security accents
plugins:
  - search # Built-in search for your notes
