site_name: KiloAlpha Security Lab
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange

nav:
  - Home: index.md # This MUST match docs/index.md
  - Networking: certs/network-plus.md
