[build]
  command = "mkdocs build"
  publish = "site"

[[edge_functions]]
  path = "/*"
  function = "auth"

# This ensures that even if a page is missing, it stays behind the password
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404